LaptopShop2/Models/TbContact.cs
using System;
using System.Collections.Generic;

namespace LaptopShop2.Models;

public partial class TbContact
{
    public int ContactId { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }

    public string? Message { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? IsRead { get; set; }
}

LaptopShop2/Areas/Admin/Controllers/TbContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaptopShop2.Models;
using X.PagedList;
using LaptopShop2.Functions;
using Microsoft.AspNetCore.Authorization;

namespace LaptopShop2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class TbContactsController : Controller
    {
        private readonly LaptopShopContext _context;

        public TbContactsController(LaptopShopContext context)
        {
            _context = context;
        }

        // GET: Admin/TbContacts
        public async Task<IActionResult> Index(int? page, string searchString)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            IQueryable<TbContact> contacts = _context.TbContacts;

            if (!string.IsNullOrEmpty(searchString))
            {
                contacts = contacts.Where(c => c.Email.Contains(searchString));
            }

            var pageContacts = await contacts.ToPagedListAsync(pageNumber, pageSize);

            ViewBag.SearchString = searchString;

            return View(pageContacts);
        }

        // GET: Admin/TbContacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbContact = await _context.TbContacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (tbContact == null)
            {
                return NotFound();
            }

            tbContact.IsRead = true;
            _context.SaveChanges();

            return View(tbContact);
        }

        // GET: Admin/TbContacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbContact = await _context.TbContacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (tbContact == null)
            {
                return NotFound();
            }

            return View(tbContact);
        }

        // POST: Admin/TbContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var tbContact = await _context.TbContacts.FindAsync(id);
                if (tbContact != null)
                {
                    _context.TbContacts.Remove(tbContact);
                }
                TempData["SuccessMessage"] = "Xóa thành công!";
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra: " + ex.Message;
                return View();
            }
        }

        private bool TbContactExists(int id)
        {
            return _context.TbContacts.Any(e => e.ContactId == id);
        }
    }
}

LaptopShop2/Areas/Admin/Views/TbContacts/Details.cshtml
@model LaptopShop2.Models.TbContact

@{
    ViewData["Title"] = "Chi tiết";
}

<div class="container-fluid">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title fw-semibold mb-4">Chi tiết</h5>
                <div class="card">
                    <div class="card-body">
                        <h4>@Model.Name</h4>
                        <div>
                            <dl class="row">
                                <dt class="col-sm-2 fw-semibold border-bottom-0">
                                    Họ và tên:
                                </dt>
                                <dd class="col-sm-10 fw-semibold border-bottom-0">
                                    @Html.DisplayFor(model => model.Name)
                                </dd>

                                <dt class="col-sm-2 fw-semibold border-bottom-0">
                                    Email:
                                </dt>
                                <dd class="col-sm-10 fw-semibold border-bottom-0">
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                                <dt class="col-sm-2 fw-semibold border-bottom-0">
                                    Tin nhắn:
                                </dt>
                                <dd class="col-sm-10 fw-semibold border-bottom-0">
                                    @Html.DisplayFor(model => model.Message)
                                </dd>
                                
                                <dt class="col-sm-2 fw-semibold border-bottom-0">
                                    Ngày gửi:
                                </dt>
                                <dd class="col-sm-10 fw-semibold border-bottom-0">
                                    @Html.DisplayFor(model => model.CreateDate)
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <div>
                    <a asp-action="Index" type="button" class="btn btn-outline-primary m-1">Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</div>

LaptopShop2/Areas/Admin/Views/TbContacts/Index.cshtml
@model IPagedList<LaptopShop2.Models.TbContact>
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Liên hệ";
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;
}

<style>
    .truncate-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 75px; /* Điều chỉnh giới hạn độ dài tùy ý */
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4">
                    <h5 class="card-title fw-semibold mb-4">Liên hệ</h5>
                    @if (!string.IsNullOrEmpty(successMessage))
                    {
                        <div id="successAlert" class="alert alert-success">
                            @successMessage
                        </div>
                    }

                    @if (!string.IsNullOrEmpty(errorMessage))
                    {
                        <div id="errorAlert" class="alert alert-danger">
                            @errorMessage
                        </div>
                    }
                    <p>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <form method="get" action="@Url.Action("Index")" class="form-inline float-end">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="searchString" placeholder="Nhập email...">
                                        <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table text-nowrap mb-0 align-middle">
                                <thead class="text-dark fs-4">
                                    <tr>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">STT</h6>
                                        </th>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Họ và tên</h6>
                                        </th>

                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Email</h6>
                                        </th>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Lời nhắn</h6>
                                        </th>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Trạng thái</h6>
                                        </th>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Ngày gửi</h6>
                                        </th>
                                        <th class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">Chức năng</h6>
                                        </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @{
                                        int i = 1;
                                    }
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="border-bottom-0">
                                                <h6 class="fw-semibold mb-0">@(i++)</h6>
                                            </td>
                                            <td class="border-bottom-0">
                                                <h6 class="fw-semibold mb-0">@item.Name</h6>
                                            </td>


                                            <td class="border-bottom-0">
                                                <h6 class="fw-semibold mb-0 truncate-text">@item.Email</h6>
                                            </td>
                                            <td class="border-bottom-0">
                                                <h6 class="fw-semibold mb-0 truncate-text">@item.Message</h6>
                                            </td>
                                            <td class="border-bottom-0">
                                                <div class="d-flex align-items-center gap-2">
                                                    @if (item.IsRead.GetValueOrDefault())
                                                    {
                                                        <span class="badge bg-secondary rounded-3 fw-semibold">Đã đọc</span>
                                                    }
                                                    else
                                                    {
                                                        <span class="badge bg-danger rounded-3 fw-semibold">Chưa đọc</span>
                                                    }
                                                </div>
                                            </td>
                                            <td class="border-bottom-0">
                                                <h6 class="fw-semibold mb-0">@item.CreateDate?.ToString("dd-MM-yyyy")</h6>
                                            </td>
                                            <td class="border-bottom-0">
                                                <a asp-action="Details" asp-route-id="@item.ContactId" class="btn btn-info btn-sm btn-detail">Chi tiết</a> |
                                                <a href="#" class="btn btn-warning btn-sm btn-delete" data-id="@item.ContactId">Xóa</a>
                                                <!-- Form ẩn để thực hiện hành động xóa -->
                                                <form id="deleteForm-@item.ContactId" method="post" action="@Url.Action("Delete", "TbContacts", new { id = item.ContactId })" style="display: none;">
                                                    @Html.AntiForgeryToken()
                                                </form>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions { Display = PagedListDisplayMode.IfNeeded, LiElementClasses = new[] { "page-link" } })
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $(".btn-delete").click(function (e) {
                e.preventDefault(); // Ngăn chặn hành động mặc định của thẻ <a>
                var contactId = $(this).data("id");
                if (confirm("Bạn có chắc chắn muốn xóa?")) {
                    $("#deleteForm-" + contactId).submit(); // Nộp form ẩn tương ứng
                }
            });
        });
    </script>
}