LaptopShop2/Models/TbOrder.cs
using System;
using System.Collections.Generic;

namespace LaptopShop2.Models;

public partial class TbOrder
{
    public int OrderId { get; set; }

    public string? Code { get; set; }

    public string? CustomerName { get; set; }

    public string? Phone { get; set; }

    public string? Address { get; set; }

    public string? Message { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CustomerId { get; set; }

    public int? OrderStatusId { get; set; }

    public bool? IsActive { get; set; }

    public virtual TbCustomer? Customer { get; set; }

    public virtual TbOrderStatus? OrderStatus { get; set; }

    public virtual ICollection<TbOrderDetail> TbOrderDetails { get; set; } = new List<TbOrderDetail>();
}

LaptopShop2/Areas/Admin/Controllers/TbOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaptopShop2.Models;
using X.PagedList;
using LaptopShop2.Functions;
using Microsoft.AspNetCore.Authorization;

namespace LaptopShop2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class TbOrdersController : Controller
    {
        private readonly LaptopShopContext _context;
        private readonly ILogger<TbOrdersController> _logger;

        public TbOrdersController(LaptopShopContext context, ILogger<TbOrdersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Admin/TbOrders
        public async Task<IActionResult> Index(int? page, string searchString)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            IQueryable<TbOrder> order = _context.TbOrders
                                                .Include(t => t.Customer)
                                                .Include(t => t.OrderStatus)
                                                .Include(t => t.TbOrderDetails)
                                                .ThenInclude(od => od.Product);

            if (!string.IsNullOrEmpty(searchString))
            {
                order = order.Where(o => o.CustomerName.Contains(searchString));
            }

            var pageOrders = await order.ToPagedListAsync(pageNumber, pageSize);

            var orderStatuses = await _context.TbOrderStatuses.ToListAsync();
            ViewBag.OrderStatuses = new SelectList(orderStatuses, "OrderStatusId", "Name");

            return View(pageOrders);
        }

        // GET: Admin/TbOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbOrder = await _context.TbOrders
                                        .Include(t => t.Customer)
                                        .Include(t => t.OrderStatus)
                                        .Include(t => t.TbOrderDetails)
                                        .ThenInclude(od => od.Product)
                                        .FirstOrDefaultAsync(m => m.OrderId == id);
            if (tbOrder == null)
            {
                return NotFound();
            }

            var orderStatuses = await _context.TbOrderStatuses.ToListAsync();
            ViewBag.OrderStatuses = new SelectList(orderStatuses, "OrderStatusId", "Name");

            return View(tbOrder);
        }
        // GET: Admin/TbOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbOrder = await _context.TbOrders
                .Include(t => t.Customer)
                .Include(t => t.OrderStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (tbOrder == null)
            {
                return NotFound();
            }

            return View(tbOrder);
        }

        // POST: Admin/TbOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbOrder = await _context.TbOrders.FindAsync(id);
            if (tbOrder != null)
            {
                _context.TbOrders.Remove(tbOrder);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbOrderExists(int id)
        {
            return _context.TbOrders.Any(e => e.OrderId == id);
        }


        [HttpPost]
        public IActionResult UpdateOrderStatus(int orderId, int orderStatusId)
        {
            var order = _context.TbOrders.FirstOrDefault(o => o.OrderId == orderId);
            if (order != null)
            {
                var status = _context.TbOrderStatuses.FirstOrDefault(s => s.OrderStatusId == orderStatusId);
                if (status != null)
                {
                    order.OrderStatusId = orderStatusId;
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Trạng thái đơn hàng đã được cập nhật thành công.";
                }
                else
                {
                    TempData["ErrorMessage"] = "Trạng thái đơn hàng không tồn tại.";
                }
            }
            else
            {
                TempData["ErrorMessage"] = "Đơn hàng không tồn tại.";
            }
            return RedirectToAction("Index");
        }

    }
}

LaptopShop2/Areas/Admin/Views/TbOrders/Details.cshtml
@model LaptopShop2.Models.TbOrder
@using LaptopShop2.Functions;

@{
    ViewData["Title"] = "Chi tiết";
}

<div class="container-fluid">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="fw-semibold mb-3">Đơn hàng của @Model.CustomerName</h5>
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Mã đơn hàng:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.Code)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Người nhận:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.CustomerName)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Điện thoại:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.Phone)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Địa chỉ:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.Address)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Lời nhắn:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.Message)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Thời gian mua:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.CreatedDate)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Người đặt:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @Html.DisplayFor(model => model.Customer.FullName)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Trạng thái đơn hàng:
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                <form asp-action="UpdateOrderStatus" method="post" id="orderStatusForm-@Model.OrderId">
                                    <input type="hidden" name="orderId" value="@Model.OrderId" />
                                    <select asp-for="@Model.OrderStatusId" asp-items="ViewBag.OrderStatuses" name="orderStatusId" class="form-control order-status-select">
                                        <option value="">-- Chọn trạng thái --</option>
                                    </select>
                                </form>
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="mt-4">
                    <a asp-action="Index" class="btn btn-secondary">Quay lại</a>
                </div>

                <!-- Bảng hiển thị sản phẩm -->
                <div class="card mt-4">
                    <div class="card-body">
                        <h5 class="fw-semibold mb-3">Danh sách sản phẩm</h5>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th class="fw-semibold text-center align-middle">Hình ảnh</th>
                                        <th class="fw-semibold text-center align-middle">Tên sản phẩm</th>
                                        <th class="fw-semibold text-center align-middle">Giá</th>
                                        <th class="fw-semibold text-center align-middle">Số lượng</th>
                                        <th class="fw-semibold text-center align-middle">Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int i = 1;
                                    }
                                    @foreach (var orderDetail in Model.TbOrderDetails)
                                    {
                                        <tr>
                                            <td style="text-center align-middle">@(i++)</td>
                                            <td class="text-center align-middle">
                                                <img src="@orderDetail.Product.Image" alt="@orderDetail.Product.ProductName" class="img-fluid" style="max-width: 125px; max-height: 50px;" />
                                            </td>
                                            <td>@orderDetail.Product.ProductName</td>
                                            <td>@Function.FormatCurrency(orderDetail.Product.DiscountedPrice)</td>
                                            <td>@orderDetail.Quantity</td>
                                            <td class="text-right">@Function.FormatCurrency((decimal)(orderDetail.Product.DiscountedPrice * orderDetail.Quantity))</td>
                                        </tr>
                                    }
                                    <tr>
                                        <td colspan="5" class="text-right fw-bold">Tổng cộng:</td>
                                        <td class="text-right fw-bold">@Function.FormatCurrency((decimal)Model.TotalAmount)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $(".order-status-select").change(function () {
                var formId = $(this).closest("form").attr("id");
                $("#" + formId).submit();
            });
        });
    </script>
}

LaptopShop2/Areas/Admin/Views/TbOrders/Index.cshtml
@model IPagedList<LaptopShop2.Models.TbOrder>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using LaptopShop2.Functions;


@{
    ViewData["Title"] = "Đơn hàng";
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;
}

<style>
    .truncate-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 75px; /* Điều chỉnh giới hạn độ dài tùy ý */
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4">
                    <h5 class="card-title fw-semibold mb-4">Đơn hàng</h5>
                    @if (!string.IsNullOrEmpty(successMessage))
                    {
                        <div id="successAlert" class="alert alert-success">
                            @successMessage
                        </div>
                    }

                    @if (!string.IsNullOrEmpty(errorMessage))
                    {
                        <div id="errorAlert" class="alert alert-danger">
                            @errorMessage
                        </div>
                    }
                    <div class="row mb-3">
                        <div class="float-right">
                            <form method="get" action="@Url.Action("Index")" class="form-inline float-end">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="searchString" placeholder="Nhập tên khách hàng...">
                                    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-nowrap mb-0 align-middle">
                            <thead class="text-dark fs-4">
                                <tr>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">STT</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Mã đơn hàng</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Người nhận</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Số điện thoại</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Địa chỉ</h6>
                                    </th>
                                    
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Ghi chú</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Sản phẩm</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Tổng tiền</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Trạng thái</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Chức năng</h6>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                @{
                                    int i = 1;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">@(i++)</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Code</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.CustomerName</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Phone</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Address</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Message</h6>
                                        </td>
                                        
                                        <td class="border-bottom-0">
                                            @foreach (var orderDetail in item.TbOrderDetails)
                                            {
                                                <div class="fw-semibold mb-0 truncate-text">
                                                    <span>@orderDetail.Product.ProductName</span>
                                                    <span>(@orderDetail.Quantity)</span>
                                                </div>
                                            }
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@Function.FormatCurrency((decimal)item.TotalAmount)</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <form asp-action="UpdateOrderStatus" method="post" class="orderStatusForm" id="orderStatusForm-@item.OrderId">
                                                <input type="hidden" name="orderId" value="@item.OrderId" />
                                                <select asp-for="@item.OrderStatusId" asp-items="ViewBag.OrderStatuses" name="orderStatusId" class="form-control order-status-select">
                                                    <option value="">-- Chọn trạng thái --</option>
                                                </select>
                                            </form>
                                        </td>

                                        <td class="border-bottom-0">
                                            <a asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-info btn-sm btn-detail">Chi tiết</a> |
                                            <a href="#" class="btn btn-warning btn-sm btn-delete" data-id="@item.OrderId">Xóa</a>
                                            <!-- Form ẩn để thực hiện hành động xóa -->
                                            <form id="deleteForm-@item.OrderId" method="post" action="@Url.Action("Delete", "TbOrders", new { id = item.OrderId })"
                                            style="display: none;">
                                                @Html.AntiForgeryToken()
                                            </form>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="pagination">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
                        { Display = PagedListDisplayMode.IfNeeded, LiElementClasses = new[] { "page-link" } })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".order-status-select").change(function () {
                var formId = $(this).closest("form").attr("id");
                $("#" + formId).submit();
            });

            $(".btn-delete").click(function (e) {
                e.preventDefault();
                var orderId = $(this).data("id");
                if (confirm("Bạn có chắc chắn muốn xóa?")) {
                    $("#deleteForm-" + orderId).submit();
                }
            });
        });
    </script>
}