LaptopShop2/Models/TbNews.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaptopShop2.Models;

public partial class TbNews
{
    public int NewId { get; set; }

    public string? Title { get; set; }

    public string? Description { get; set; }

    public string? Detail { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public string? Image { get; set; }

    public string? Tags { get; set; }

    public int? CategoryNewId { get; set; }

    public bool IsActive { get; set; }

    public virtual TbCategoryNew? CategoryNew { get; set; }
    [NotMapped]
    public string? CategoryInput {  get; set; }

    internal TbNews Where(Func<object, bool> value)
    {
        throw new NotImplementedException();
    }
}

LaptopShop2/Areas/Admin/Controllers/TbNewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaptopShop2.Models;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace LaptopShop2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class TbNewsController : Controller
    {
        private readonly LaptopShopContext _context;

        public TbNewsController(LaptopShopContext context)
        {
            _context = context;
        }

        // GET: Admin/TbNews
        public async Task<IActionResult> Index(int? page, string searchString)
        {

            
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var news = _context.TbNews.Include(t => t.CategoryNew).OrderByDescending(b => b.CreatedDate);

            if (!string.IsNullOrEmpty(searchString))
            {
                news = (IOrderedQueryable<TbNews>)news.Where(b => b.Title.Contains(searchString));
            }

            var pageList = await news.ToPagedListAsync(pageNumber, pageSize);
            ViewBag.SearchString = searchString;
            return View(pageList);
        }

        // GET: Admin/TbNews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbNews = await _context.TbNews
                .Include(t => t.CategoryNew)
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (tbNews == null)
            {
                return NotFound();
            }

            return View(tbNews);
        }

        // GET: Admin/TbNews/Create
        public IActionResult Create()
        {
            ViewData["CategoryNewId"] = new SelectList(_context.TbCategoryNews, "CategoryNewId", "Name");
            var news = new TbNews
            {
                CreatedDate = DateTime.Now
            };
            return View(news);
        }

        // POST: Admin/TbNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewId,Title,Description,Detail,CreatedDate,CreatedBy,Image,Tags,CategoryNewId,IsActive")] TbNews tbNews, string CategoryInput)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!string.IsNullOrEmpty(CategoryInput))
                    {
                        var CategoryName = _context.TbCategoryNews.FirstOrDefault(c => c.Name == CategoryInput);
                        if (CategoryName == null)
                        {
                            var newCategoryName = new TbCategoryNew { Name = CategoryInput };
                            _context.TbCategoryNews.Add(newCategoryName);
                            await _context.SaveChangesAsync();

                            tbNews.CategoryNewId = newCategoryName.CategoryNewId;
                        }
                        else
                        {
                            tbNews.CategoryNewId = CategoryName.CategoryNewId;
                        }
                    }
                    _context.Add(tbNews);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Thêm tin tức thành công!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Lỗi:" + ex.Message);
                    TempData["ErrorMessage"] = "Có lỗi xảy ra. Vui lòng thử lại!";
                }
            }
            ViewData["CategoryNewId"] = new SelectList(_context.TbCategoryNews, "CategoryNewId", "Name", tbNews.CategoryNewId);
            return View(tbNews);
        }

        // GET: Admin/TbNews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbNews = await _context.TbNews.FindAsync(id);
            if (tbNews == null)
            {
                return NotFound();
            }
            ViewData["CategoryNewId"] = new SelectList(_context.TbCategoryNews, "CategoryNewId", "Name", tbNews.CategoryNewId);
            return View(tbNews);
        }

        // POST: Admin/TbNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewId,Title,Description,Detail,CreatedDate,CreatedBy,Image,Tags,CategoryNewId,IsActive")] TbNews tbNews)
        {
            if (id != tbNews.NewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbNews);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Tin tức đã được chỉnh sửa!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbNewsExists(tbNews.NewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryNewId"] = new SelectList(_context.TbCategoryNews, "CategoryNewId", "Name", tbNews.CategoryNewId);
            return View(tbNews);
        }

        // GET: Admin/TbNews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbNews = await _context.TbNews
                .Include(t => t.CategoryNew)
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (tbNews == null)
            {
                return NotFound();
            }

            return View(tbNews);
        }

        // POST: Admin/TbNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var tbBlog = await _context.TbNews.FindAsync(id);
                if (tbBlog != null)
                {
                    _context.TbNews.Remove(tbBlog);
                }
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Đã xóa Tin tức!";
            }
            catch (Exception ex)
            {
                Console.WriteLine("Lỗi: " + ex.Message);
                TempData["ErrorMessage"] = "Có lỗi xảy ra. Vui lòng thử lại!";
            }
            return RedirectToAction(nameof(Index));
        }

        private bool TbNewsExists(int id)
        {
            return _context.TbNews.Any(e => e.NewId == id);
        }
    }
}

LaptopShop2/Areas/Admin/Views/TbNews/Create.cshtml
@model LaptopShop2.Models.TbNews

@{
    ViewData["Title"] = "Thêm tin tức";
}

<div class="container-fluid">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title fw-semibold mb-4">Thêm tin tức</h5>
                <div class="card">
                    <div class="card-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group mb-3">
                                <label asp-for="Title" class="control-label form-label">Tiêu đề</label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>

                            <div class="form-group mb-3">
                                <label asp-for="Description" class="control-label form-label">Mô tả</label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="Detail" class="control-label form-label">Nội dung</label>
                                <textarea asp-for="Detail" class="form-control"></textarea>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="Image" class="control-label form-label form-label form-label">Hình ảnh</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button type="button" class="btn btn-success m-1 form-label" onclick="openDialog('file_input')">Chọn hình ảnh</button>
                                    </div>
                                    <!-- /btn-group -->
                                    <input type="text" class="form-control " id="file_input" asp-for="Image" aria-describedby="button-addon2">
                                </div>
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                            <div class="form-group  mb-3">
                                <label asp-for="CreatedDate" class="control-label form-label">Ngày tạo</label>
                                <input asp-for="CreatedDate" class="form-control" />
                                <span asp-validation-for="CreatedDate" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="CreatedBy" class="control-label form-label">Người tạo</label>
                                <input asp-for="CreatedBy" class="form-control" />
                                <span asp-validation-for="CreatedBy" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="Tags" class="control-label form-label"></label>
                                <input asp-for="Tags" class="form-control" />
                                <span asp-validation-for="Tags" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3 form-check form-switch bottom-0 fw-semibold">
                                <input class="form-check-input" type="checkbox" asp-for="IsActive" />Hiển thị
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="CategoryNewId" class="control-label form-label">Chọn hoặc nhập danh mục</label>
                                <input type="text" asp-for="CategoryNewId" name="categoryInput" id="categoryInput" list="Category" class="form-control" />
                                <datalist id="Category">
                                    @foreach (var item in (IEnumerable<SelectListItem>)ViewData["CategoryNewId"])
                                    {
                                        <option value="@item.Text"></option>
                                    }
                                </datalist>
                            </div>

                            <div class="form-group mb-3">
                                <input type="submit" value="Thêm mới" class="btn btn-primary" /> |
                                <a asp-action="Index" type="button" class="btn btn-outline-primary m-1">Quay lại</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var summerNote = new LaptopShop2.Areas.Admin.Models.SummerNote("#Detail");
}
<partial name="_SummerNote" model="summerNote" />

LaptopShop2/Areas/Admin/Views/TbNews/Details.cshtml
@model LaptopShop2.Models.TbNews

@{
    ViewData["Title"] = "Chi tiết";
}


<div class="container-fluid">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-5 fw-semibold">Tin tức: @Model.Title</h5>
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Tiêu đề
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Title)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Mô tả
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Description)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Nội dung
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Detail)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Ngày tạo
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.CreatedDate)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Người tạo
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.CreatedBy)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                @Html.DisplayNameFor(model => model.Tags)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Tags)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Đường dẫn hình ảnh:
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Image)
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Hiển thị
                            </dt>
                            <dd class="col-sm-10 fw-semibold border-bottom-0">
                                @if (Model.IsActive)
                                {
                                    <span class="text-success">Có</span>
                                }
                                else
                                {
                                    <span class="text-danger">Không</span>
                                }
                            </dd>
                            <dt class="col-sm-2 fw-semibold border-bottom-0">
                                Danh mục:
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.CategoryNew.Name)
                            </dd>
                        </dl>
                        <div>
                            <a class="btn btn-danger m-1" asp-action="Edit" asp-route-id="@Model?.NewId">Edit</a> |
                            <a class="btn btn-outline-primary m-1" asp-action="Index">Quay lại</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LaptopShop2/Areas/Admin/Views/TbNews/Index.cshtml
@model IPagedList<LaptopShop2.Models.TbNews>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewData["Title"] = "Tin tức";
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;
}

<style>
    .truncate-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 75px; /* Điều chỉnh giới hạn độ dài tùy ý */
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4">
                    <h5 class="card-title fw-semibold mb-4">Quản lý Blog</h5>
                    @if (!string.IsNullOrEmpty(successMessage))
                    {
                        <div id="successAlert" class="alert alert-success">
                            @successMessage
                        </div>
                    }

                    @if (!string.IsNullOrEmpty(errorMessage))
                    {
                        <div id="errorAlert" class="alert alert-danger">
                            @errorMessage
                        </div>
                    }
                    <div class="row mb-3">
                        <div class="col-sm-6">
                            <p>
                                <a asp-action="Create" class="btn btn-primary mb-3">Thêm mới</a>
                            </p>
                        </div>
                        <div class="col-sm-6">
                            <form method="get" action="@Url.Action("Index")" class="form-inline float-end">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="searchString" placeholder="Nhập từ khóa...">
                                    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-nowrap mb-0 align-middle">
                            <thead class="text-dark fs-4">
                                <tr>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">STT</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Tiêu đề</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Mô tả</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Chi tiết</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Hình ảnh</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Ngày tạo</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Tạo bởi</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Hiển thị</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Danh mục</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Chức năng</h6>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                @{
                                    int i = 1;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">@(i++)</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Title</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Description</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.Detail)</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <img style="max-width: 50px;height: 40px; object-fit: cover;" src="@item.Image" />
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">@item.CreatedDate?.ToString("dd-MM-yyyy")</h6>
                                        </td>

                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0 truncate-text">@item.CreatedBy</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <div class="d-flex align-items-center gap-2">
                                                @if (item.IsActive)
                                                {
                                                    <span class="badge bg-secondary rounded-3 fw-semibold">Có</span>
                                                }
                                                else
                                                {
                                                    <span class="badge bg-danger rounded-3 fw-semibold">Không</span>
                                                }
                                            </div>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">
                                                @if (item.CategoryNewId != null)
                                                {
                                                    @item.CategoryNew.Name
                                                }
                                                else
                                                {
                                                    <text>Không</text>
                                                }
                                            </h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <a asp-action="Edit" asp-route-id="@item.NewId" class="btn btn-danger btn-sm btn-edit">Sửa</a> |
                                            <a asp-action="Details" asp-route-id="@item.NewId" class="btn btn-info btn-sm btn-detail">Chi tiết</a> |
                                            <a href="#" class="btn btn-warning btn-sm btn-delete" data-id="@item.NewId">Xóa</a>
                                            <!-- Form ẩn để thực hiện hành động xóa -->
                                            <form id="deleteForm-@item.NewId" method="post" action="@Url.Action("Delete", "TbNews", new { id = item.NewId })" style="display: none;">
                                                @Html.AntiForgeryToken()
                                            </form>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="pagination">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions { Display = PagedListDisplayMode.IfNeeded, LiElementClasses = new[] { "page-link" } })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".btn-delete").click(function (e) {
                e.preventDefault(); // Ngăn chặn hành động mặc định của thẻ <a>
                var newId = $(this).data("id");
                if (confirm("Bạn có chắc chắn muốn xóa?")) {
                    $("#deleteForm-" + newId).submit(); // Nộp form ẩn tương ứng
                }
            });
        });
    </script>
}